//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукция
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Продукция()
        {
            this.Состав_заказа = new HashSet<Состав_заказа>();
        }
    
        public long id_продукции { get; set; }
        public string Артикул { get; set; }
        public string Название { get; set; }
        public string Единица_измерения { get; set; }
        public int Размер_максимальной_скидки_в_процентах { get; set; }
        public string Производитель { get; set; }
        public long id_категории_продукции { get; set; }
        public int Действущая_скидка_в_процентах { get; set; }
        public int Количество_на_складе { get; set; }
        public int Минимальный_остаток { get; set; }
        public string Описание { get; set; }
        public byte[] Изображение { get; set; }
        public long id_заявки { get; set; }
    
        public virtual Заявки Заявки { get; set; }
        public virtual Категории_продукции Категории_продукции { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Состав_заказа> Состав_заказа { get; set; }
    }
}
